/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'},
    // {
    //   type: 'category',
    //   label: 'API links',
    //   items: [
    //     {
    //       type: 'link',
    //       label: 'Python SDK',
    //       href: 'https://github.com/aronbrand/astriaclient',
    //     },
    //     {
    //       type: 'link',
    //       label: 'Postman',
    //       href: 'https://documenter.getpostman.com/view/273068/2s8YmSrfgD',
    //     },
    //     {
    //       type: 'link',
    //       label: 'Bubble.io Plugin',
    //       href: 'https://bubble.io/plugin/astria-api---stable-diffusion-1674501522435x732640117689417700',
    //     },
    //     {
    //       type: 'link',
    //       label: 'API key',
    //       href: 'https://www.astria.ai/users/edit#api',
    //     },
    //
    //   ]
    // }
  ],


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
